--------------------------------DROPS--------------------------------------
drop table if exists Formacion;
drop table if exists Cui_ext_ser;
drop table if exists Cui_ext;
drop table if exists Ser_est;
drop table if exists Hist_pago;
drop table if exists Tdc;
drop table if exists Intercambio;
drop table if exists Estatus;
drop table if exists Calificacion;
drop table if exists Servicio;
drop table if exists Usu_acc;
drop table if exists Extra;
drop table if exists Horario;
drop table if exists Perro;
drop table if exists Call_center;
drop table if exists Owner;
drop table if exists Cuidador;
drop table if exists Usuario;
drop table if exists Accion;
drop table if exists Uso;
drop table if exists Tarea;
drop table if exists Lugar;
drop table if exists Raza;
drop table if exists Eliminado;
drop table if exists Constante;

-------------------------------CREATES-------------------------------------

Create table Raza(
raz_id serial not null unique,
raz_nombre varchar(50) not null,
Constraint pk_id_raza primary key (raz_id)
);

Create table Constante(
con_id serial not null unique,
con_identificador varchar(50) not null,
con_valor varchar(50)not null,
Constraint pk_id_constante primary key (con_id)
);

Create table Eliminado(
eli_id serial not null unique,
eli_correo varchar(50) not null,
Constraint pk_id_eliminado primary key (eli_id)
);

Create table Lugar(
lug_id serial unique,
lug_nombre varchar(50) not null,
lug_tipo varchar(20) not null,
lug_fk_lugar integer,
Constraint pk_id_lugar primary key (lug_id),
Constraint fk_lugar_lugar foreign key (lug_fk_lugar) references Lugar(lug_id),
Constraint check_tipo_lugar check (lug_tipo IN('pais','estado','municipio','parroquia'))
);

Create table Tarea(
tar_id serial unique,
tar_nombre varchar(200) not null,
Constraint pk_id_tarea primary key (tar_id)
);

Create table Usuario(
usu_id serial not null unique,
usu_nombre1 varchar(50) not null,
usu_nombre2 varchar(50),
usu_apellido1 varchar(50) not null,
usu_apellido2 varchar(50),
usu_fecha_nacimiento date not null,
usu_correo varchar(50) not null unique,
usu_foto_perfil varchar(100),
usu_telefono varchar(50) not null,
usu_fk_lugar integer not null,
usu_api_key varchar(200),
usu_tipo varchar(10) not null,
Constraint pk_id_usuario primary key (usu_id),
Constraint fk_lugar_usuario foreign key (usu_fk_lugar) references Lugar(lug_id),
Constraint check_tipo_usuario check(usu_tipo IN ('cuidador','owner'))
);

Create table Cuidador(
cui_id serial not null unique,
cui_capacidad_maxima integer not null,
cui_tarifa_diaria real not null,
cui_biografia varchar(150),
cui_fk_usuario integer not null unique,
Constraint pk_id_cuidador primary key (cui_id),
Constraint fk_usuario_cuidador foreign key (cui_fk_usuario) references Usuario(usu_id) on delete cascade
);

Create table Owner(
own_id serial not null unique,
own_fk_usuario integer not null unique,
Constraint pk_id_owner primary key (own_id),
Constraint fk_usuario_owner foreign key (own_fk_usuario) references Usuario(usu_id) on delete cascade
);

create table call_center(
cal_id serial not null unique,
cal_nombre varchar(50) not null,
cal_apellido varchar(50) not null,
cal_fecha_nacimiento date not null,
cal_correo varchar(50) not null unique,
cal_telefono varchar(15) not null,
cal_password varchar(50) not null,
cal_tipo_usuario varchar(10) not null,
Constraint pk_id_call_center primary key (cal_id),
Constraint check_tipo_usuario check(cal_tipo_usuario IN ('supervisor','operador'))
);

Create table Perro(
per_id serial not null unique,
per_nombre varchar(50) not null,
per_microchip varchar(2) not null,
per_color varchar(50) not null,
per_peso real not null,
per_fecha_nacimiento date not null,
per_altura real not null,
per_referencia varchar(200),
per_fk_raza integer not null,
per_fk_tarea integer,
per_fk_owner integer not null,
Constraint pk_id_perro primary key (per_id),
Constraint fk_raza_perro foreign key (per_fk_raza) references Raza(raz_id),
Constraint fk_owner_perro foreign key (per_fk_owner) references Owner(own_id) on delete cascade,
Constraint fk_tarea_perro foreign key (per_fk_tarea) references Tarea(tar_id),
Constraint check_microchip_perro check(per_microchip IN('si','no'))
);

Create table Horario(
hor_id serial not null unique,
hor_fecha_inicio date not null,
hor_fecha_fin date not null,
hor_fk_cuidador integer not null,
Constraint pk_id_horario primary key (hor_id),
Constraint fk_cuidador_horario foreign key (hor_fk_cuidador) references Cuidador(cui_id) on delete cascade
);

Create table Extra(
ext_id serial not null unique,
ext_nombre varchar(100) not null,
Constraint pk_id_extra primary key (ext_id)
);

Create table Cui_ext(
cxt_id serial not null unique,
cxt_fk_extra integer not null,
cxt_fk_cuidador integer not null,
cxt_precio real not null,
Constraint pk_id_cui_ext primary key (cxt_id),
Constraint fk_extra_cui_ext foreign key (cxt_fk_extra) references Extra(ext_id) on delete cascade,
Constraint fk_cuidador_cui_ext foreign key (cxt_fk_cuidador) references Cuidador(cui_id) on delete cascade
);
									   							   
Create table Accion(
acc_id serial not null unique,
acc_correo varchar(50) not null,
acc_fecha timestamp not null,
acc_descripcion varchar(50) not null,
Constraint pk_id_accion primary key (acc_id)
);

Create table Servicio(
ser_id serial not null unique,
ser_fecha_inicio date not null,
ser_fecha_fin date not null,
ser_fk_owner integer not null,
ser_fk_cuidador integer not null,
ser_fk_perro integer not null,
ser_precio float,
ser_payemntid varchar(50),
ser_chargeid varchar(50),
Constraint pk_id_servicio primary key (ser_id),
Constraint fk_owner_servicio foreign key (ser_fk_owner) references Usuario(usu_id) on delete cascade,
Constraint fk_perro_servicio foreign key (ser_fk_perro) references Perro(per_id) on delete cascade,
Constraint fk_cuidador_servicio foreign key (ser_fk_cuidador) references Usuario(usu_id) on delete cascade
);

Create table Calificacion(
clf_id serial not null unique,
clf_puntuacion integer not null,
clf_comentario varchar(200) not null,
clf_fecha date not null,
clf_fk_servicio integer not null,
Constraint pk_id_calificacion primary key (clf_id),
Constraint fk_servicio_calificacion foreign key (clf_fk_servicio) references Servicio(ser_id) on delete cascade
);

Create table Cui_ext_ser(
cxs_id serial not null unique,
csx_fk_cui_ext integer not null,
csx_fk_servicio integer not null,
Constraint pk_id_cui_ext_ser primary key (cxs_id),
Constraint fk_cui_ext_csx foreign key (csx_fk_cui_ext) references Cui_ext(cxt_id) on delete cascade,
Constraint fk_servicio_csx foreign key (csx_fk_servicio) references Servicio(ser_id) on delete cascade
);

Create table Intercambio(
int_id serial not null unique,
int_descripcion varchar(200) not null,
Constraint pk_intercambio primary key (int_id)
);

Create table Tdc(
tdc_id serial not null unique,
tdc_codigo_seguridad varchar(50) not null unique,
tdc_banco varchar(30) not null,
tdc_tipo varchar(20) not null,
tdc_fecha_vencimiento date not null,
tdc_fk_owner integer not null,
Constraint fk_tdc_owner foreign key (tdc_fk_owner) references Owner(own_id)
);

Create table Hist_pago(
his_fecha_pago date not null,
his_monto_total real not null,
his_fk_servicio integer not null,
Constraint fk_servicio_hist_pago foreign key (his_fk_servicio) references Servicio(ser_id) on delete cascade
); 

Create table Estatus(
est_id serial not null unique,
est_fecha_cambio date not null,
est_nombre varchar(50) not null,
est_fk_servicio integer not null,
Constraint pk_ser_est primary key (est_id),
Constraint fk_servicio_est foreign key (est_fk_servicio) references Servicio(ser_id) on delete cascade,
Constraint check_estatus_servicio check(est_nombre IN('Reservado','En proceso', 'Cancelado', 'Finalizado'))
);

/*Create table Formacion(
for_id serial not null unique,
for_fk_tarea integer not null,
for_fk_perro integer not null,
Constraint pk_formacion primary key (for_id),
Constraint fk_tarea_formacion foreign key (for_fk_tarea) references Tarea(tar_id),
Constraint fk_perro_formacion foreign key (for_fk_perro) references Perro(per_id)
);*/

INSERT INTO Raza (raz_nombre) values 
('Affenpinscher'),
('Afghan Hound'),
('Africanis'),
('Aidi'),
('Airedale Terrier'),
('Akbash Dog'),
('Akita Inu'),
('Alangu Mastiff'),
('Alano Español'),
('Alapaha Blue Blood Bulldog'),
('Alaskan Klee Kai'),
('Alaskan Malamute'),
('Alaunt'),
('Alopekis'),
('Alpine Dachsbracke'),
('Alsatian Shepalute'),
('American Akita'),
('American Bulldog'),
('American Cocker Spaniel'),
('American Eskimo Dog'),
('American Foxhound'),
('American Hairless Terrier'),
('American Mastiff'),
('American Pit Bull Terrier'),
('American Staffordshire Terrier'),
('American Water Spaniel'),
('Anatolian Shepherd Dog'),
('Anglo-Français de Petite Vénerie'),
('Appenzeller Sennenhund'),
('Argentine Dogo'),
('Ariege Pointer'),
('Ariegeois'),
('Armant'),
('Artois Hound'),
('Australian Bulldog'),
('Australian Cattle Dog'),
('Australian Kelpie'),
('Australian Shepherd'),
('Australian Silky Terrier'),
('Australian Stumpy Tail Cattle Dog'),
('Australian Terrier'),
('Austrian Black and Tan Hound'),
('Austrian Pinscher'),
('Azawakh'),
('Bakharwal Dog'),
('Barbet'),
('Basenji'),
('Basque Shepherd Dog'),
('Basset Artésien Normand'),
('Basset Bleu de Gascogne'),
('Basset Fauve de Bretagne'),
('Grand Basset Griffon Vendéen'),
('Petit Basset Griffon Vendéen'),
('Bavarian Mountain Hound'),
('Beagle'),
('Beagle-Harrier'),
('Bearded Collie'),
('Beauceron'),
('Bedlington Terrier'),
('Belgian Shepherd Dog'),
('Belgian Shepherd Dog (Groenendael)'),
('Belgian Shepherd Dog (Laekenois)'),
('Belgian Shepherd Dog (Malinois)'),
('Belgian Shepherd (Tervuren)'),
('Bergamasco Shepherd'),
('Berger Blanc Suisse'),
('Berger Picard'),
('Berner Laufhund'),
('Bernese Mountain Dog'),
('Bichon Frisé'),
('Billy'),
('Bisben'),
('Black and Tan Coonhound'),
('Black and Tan Virginia Foxhound'),
('Bullenbeisser'),
('Black Norwegian Elkhound'),
('Black Russian Terrier'),
('Blackmouth Cur'),
('Grand Bleu de Gascogne'),
('Petit Bleu de Gascogne'),
('Bloodhound'),
('Blue Lacy'),
('Blue Paul Terrier'),
('Bluetick Coonhound'),
('Boerboel'),
('Bohemian Shepherd'),
('Bolognese'),
('Border Collie'),
('Border Terrier'),
('Borzoi'),
('Bosnian Coarse-haired Hound'),
('Boston Terrier'),
('Bouvier des Ardennes'),
('Bouvier des Flandres'),
('Boxer'),
('Boykin Spaniel'),
('Bracco Italiano'),
('Braque dAuvergne'),
('Braque du Bourbonnais'),
('Braque du Puy'),
('Braque Francais'),
('Braque Saint-Germain'),
('Brazilian Terrier'),
('Briard'),
('Briquet Griffon Vendéen'),
('Brittany'),
('Broholmer'),
('Bruno Jura Hound'),
('Bucovina Shepherd Dog'),
('Bull and Terrier'),
('Bull Terrier'),
('Bull Terrier (Miniature)'),
('Bullmastiff'),
('Bully Kutta'),
('Cairn Terrier'),
('Canaan Dog'),
('Canadian Eskimo Dog'),
('Canadian Pointer'),
('Cane Corso'),
('Cão da Serra de Aires'),
('Cão de Castro Laboreiro'),
('Cão Fila de São Miguel'),
('Carolina Dog'),
('Carpathian Shepherd Dog'),
('Catahoula Cur'),
('Catalan Sheepdog'),
('Caucasian Shepherd Dog'),
('Cavalier King Charles Spaniel'),
('Central Asian Shepherd Dog'),
('Cesky Fousek'),
('Cesky Terrier'),
('Polish Greyhound'),
('Chesapeake Bay Retriever'),
('Chien-gris'),
('Chien Français Blanc et Noir'),
('Chien Français Blanc et Orange'),
('Chien Français Tricolore'),
('Chihuahua'),
('Chilean Fox Terrier'),
('Chinese Chongqing Dog'),
('Chinese Crested Dog'),
('Chinese Imperial Dog'),
('Chinook'),
('Chippiparai'),
('Chow Chow'),
('Cimarrón Uruguayo'),
('Cierny Sery'),
('Cirneco dellEtna'),
('Clumber Spaniel'),
('Rough Collie'),
('Smooth Collie'),
('Combai'),
('Cordoba Fighting Dog'),
('Coton de Tulear'),
('Cretan Hound'),
('Croatian Sheepdog'),
('Cumberland Sheepdog'),
('Curly Coated Retriever'),
('Czechoslovakian Wolfdog'),
('Dachshund'),
('Dalmatian'),
('Dandie Dinmont Terrier'),
('Danish Swedish Farmdog'),
('Dingo'),
('Doberman Pinscher'),
('Dogue de Bordeaux'),
('Dogo Cubano'),
('Dogo Guatemalteco'),
('Dogo Sardesco'),
('Drentse Patrijshond'),
('Drever'),
('Dunker'),
('Dutch Shepherd Dog'),
('Dutch Smoushond'),
('East-European Shepherd'),
('East Siberian Laika'),
('Elo'),
('English Cocker Spaniel'),
('English Coonhound'),
('English Foxhound'),
('English Mastiff'),
('English Pointer'),
('English Setter'),
('English Shepherd'),
('English Springer Spaniel'),
('English Toy Terrier (Black & Tan)'),
('English Water Spaniel'),
('English White Terrier'),
('Entlebucher Mountain Dog'),
('Épagneul Bleu de Picardie'),
('Estonian Hound'),
('Estrela Mountain Dog'),
('Eurasier'),
('Field Spaniel'),
('Fila Brasileiro'),
('Findo'),
('Finnish Hound'),
('Finnish Lapphund'),
('Finnish Spitz'),
('Flat-Coated Retriever'),
('Formosan Mountain Dog'),
('Fox Terrier (Smooth)'),
('Wire Fox Terrier'),
('French Brittany'),
('French Bulldog'),
('French Spaniel'),
('Galgo Español'),
('German Longhaired Pointer'),
('German Pinscher'),
('German Shepherd Dog'),
('German Shorthaired Pointer'),
('German Spaniel'),
('German Spitz'),
('German Wirehaired Pointer'),
('Giant Schnauzer'),
('Glen of Imaal Terrier'),
('Golden Retriever'),
('Gordon Setter'),
('Grand Anglo-Français Blanc et Noir'),
('Grand Anglo-Français Blanc et Orange'),
('Grand Anglo-Français Tricolore'),
('Grand Griffon Vendéen'),
('Gran Mastín de Borínquen'),
('Great Dane'),
('Great Pyrenees'),
('Greater Swiss Mountain Dog'),
('Greenland Dog'),
('Greyhound'),
('Griffon Bleu de Gascogne'),
('Griffon Bruxellois'),
('Griffon Fauve de Bretagne'),
('Griffon Nivernais'),
('Gull Dong'),
('Gull Terr'),
('Hare Indian Dog'),
('Hamiltonstövare'),
('Hanover Hound'),
('Harrier'),
('Havanese'),
('Hawaiian Poi Dog'),
('Himalayan Sheepdog'),
('Hokkaido'),
('Hortaya Borzaya'),
('Hovawart'),
('Hungarian Hound'),
('New Zealand Huntaway'),
('Hygenhund'),
('Ibizan Hound'),
('Icelandic Sheepdog'),
('Indian Spitz'),
('Irish Bull Terrier'),
('Irish Red and White Setter'),
('Irish Setter'),
('Irish Staffordshire Bull Terrier'),
('Irish Terrier'),
('Irish Water Spaniel'),
('Irish Wolfhound'),
('Istrian Shorthaired Hound'),
('Istrian Coarse-haired Hound'),
('Italian Greyhound'),
('Jack Russell Terrier'),
('Jagdterrier'),
('Jämthund'),
('Japanese Chin'),
('Japanese Spitz'),
('Japanese Terrier'),
('Jonangi'),
('Kaikadi'),
('Kai Ken'),
('Kangal Dog'),
('Kanni'),
('Karakachan Dog'),
('Karelian Bear Dog'),
('Karst Shepherd'),
('Keeshond'),
('Kerry Beagle'),
('Kerry Blue Terrier'),
('King Charles Spaniel'),
('King Shepherd'),
('Kintamani'),
('Kishu'),
('Komondor'),
('Kooikerhondje'),
('Koolie'),
('Korean Jindo Dog'),
('Korean Mastiff'),
('Kromfohrländer'),
('Kunming Wolf-dog'),
('Kuri'),
('Kuvasz'),
('Kyi-Leo'),
('Labrador Husky'),
('Labrador Retriever'),
('Lagotto Romagnolo'),
('Lakeland Terrier'),
('Lancashire Heeler'),
('Landseer'),
('Lapponian Herder'),
('Leonberger'),
('Lhasa Apso'),
('Lithuanian Hound'),
('Longhaired Whippet'),
('Lottatore Brindisino'),
('Löwchen'),
('Magyar Agár'),
('Majestic Tree Hound'),
('Maltese'),
('Manchester Terrier'),
('Maremma Sheepdog'),
('McNab'),
('Mexican Hairless Dog'),
('Miniature Australian Shepherd'),
('Miniature Fox Terrier'),
('Miniature Pinscher'),
('Miniature Schnauzer'),
('Miniature Siberian Husky'),
('Mioritic'),
('Molossus'),
('Montenegrin Mountain Hound'),
('Moscow Watchdog'),
('Moscow Water Dog'),
('Mountain Cur'),
('Mountain View Cur'),
('Mucuchies'),
('Mudi'),
('Mudhol Hound'),
('Large Münsterländer'),
('Small Münsterländer'),
('Murray River Curly Coated Retriever'),
('Neapolitan Mastiff'),
('Newfoundland'),
('New Guinea Singing Dog'),
('Norfolk Spaniel'),
('Norfolk Terrier'),
('Norrbottenspets'),
('North Country Beagle'),
('Northern Inuit Dog'),
('Norwegian Buhund'),
('Norwegian Elkhound'),
('Norwegian Lundehund'),
('Norwich Terrier'),
('Nova Scotia Duck-Tolling Retriever'),
('Old Danish Pointer'),
('Old English Sheepdog'),
('Old English Bulldog'),
('Old English Terrier'),
('Old German Shepherd Dog'),
('Olde English Bulldogge'),
('Otterhound'),
('Pachon Navarro'),
('Paisley Terrier'),
('Papillon'),
('Parson Russell Terrier'),
('Patterdale Terrier'),
('Pekingese'),
('Perro de Presa Canario'),
('Perro de Presa Mallorquin'),
('Peruvian Hairless Dog'),
('Phalène'),
('Pharaoh Hound'),
('Picardy Spaniel'),
('Plott Hound'),
('Podenco Canario'),
('Pointer'),
('Polish Hound'),
('Polish Hunting Dog'),
('Polish Lowland Sheepdog'),
('Polish Tatra Sheepdog'),
('Pomeranian'),
('Pont-Audemer Spaniel'),
('Poodle'),
('Porcelaine'),
('Portuguese Podengo'),
('Portuguese Pointer'),
('Portuguese Water Dog'),
('Pražský Krysarík'),
('Pudelpointer'),
('Pug'),
('Puli'),
('Pumi'),
('Pungsan Dog'),
('Pyrenean Mastiff'),
('Pyrenean Shepherd'),
('Rafeiro do Alentejo'),
('Rajapalayam'),
('Rampur Greyhound'),
('Rastreador Brasileiro'),
('Ratonero Bodeguero Andaluz'),
('Rat Terrier'),
('Redbone Coonhound'),
('Rhodesian Ridgeback'),
('Rottweiler'),
('Russian Spaniel'),
('Russkiy Toy'),
('Russo-European Laika'),
('Russell Terrier'),
('Saarlooswolfhond'),
('Sabueso Español'),
('Sage Ashayeri'),
('Sage Mazandarani'),
('Sakhalin Husky'),
('Saluki'),
('Samoyed'),
('Sapsali'),
('Šarplaninac'),
('Schapendoes'),
('Schillerstövare'),
('Schipperke'),
('Old Croatian Sighthound'),
('Standard Schnauzer'),
('Schweizer Laufhund'),
('Schweizerischer Niederlaufhund'),
('Scotch Collie'),
('Scottish Deerhound'),
('Scottish Terrier'),
('Sealyham Terrier'),
('Segugio Italiano'),
('Seppala Siberian Sleddog'),
('Serbian Hound'),
('Serbian Tricolour Hound'),
('Shar Pei'),
('Shetland Sheepdog'),
('Shiba Inu'),
('Shih Tzu'),
('Shikoku'),
('Shiloh Shepherd Dog'),
('Shirak'),
('Siberian Husky'),
('Silken Windhound'),
('Sinhala Hound'),
('Skye Terrier'),
('Sloughi'),
('Slovak Cuvac'),
('Slovakian Rough-haired Pointer'),
('Slovenský Kopov'),
('Smålandsstövare'),
('Small Greek Domestic Dog'),
('Soft-Coated Wheaten Terrier'),
('South Russian Ovcharka'),
('Southern Hound'),
('Spanish Mastiff'),
('Spanish Water Dog'),
('Spinone Italiano'),
('Sporting Lucas Terrier'),
('St. Bernard'),
('St. Johns Water Dog'),
('Stabyhoun'),
('Staffordshire Bull Terrier'),
('Stephens Cur'),
('Styrian Coarse-haired Hound'),
('Sussex Spaniel'),
('Swedish Lapphund'),
('Swedish Vallhund'),
('Swedish Beagle'),
('Tahltan Bear Dog'),
('Taigan'),
('Tamaskan Dog'),
('Teddy Roosevelt Terrier'),
('Telomian'),
('Tenterfield Terrier'),
('Thai Bangkaew Dog'),
('Thai Ridgeback'),
('Tibetan Mastiff'),
('Tibetan Spaniel'),
('Tibetan Terrier'),
('Tornjak'),
('Tosa'),
('Toy Bulldog'),
('Toy Fox Terrier'),
('Toy Manchester Terrier'),
('Treeing Cur'),
('Treeing Walker Coonhound'),
('Tyrolean Hound'),
('Utonagan'),
('Vizsla'),
('Volpino Italiano'),
('Weimaraner'),
('Cardigan Welsh Corgi'),
('Pembroke Welsh Corgi'),
('Welsh Sheepdog'),
('Welsh Springer Spaniel'),
('Welsh Terrier'),
('West Highland White Terrier'),
('West Siberian Laika'),
('Westphalian Dachsbracke'),
('Wetterhoun'),
('Whippet'),
('White English Bulldog'),
('White Shepherd Dog'),
('Wirehaired Vizsla'),
('Wirehaired Pointing Griffon'),
('Yorkshire Terrier');

INSERT INTO Extra (ext_nombre) values 
('Jornada de 8hrs extra en su casa'),
('Jornada de 8hrs extra en mi casa'),
('Caminata de 30 minutos'),
('Sesión de fotos - cantidad:10'),
('Baño'),
('Corte de uñas'),
('Limpieza de oídos'),
('Cepillado de dientes'),
('Paseos por la playa'),
('Traslado a otro lugar de la ciudad');

INSERT INTO tarea (tar_nombre) values 
('Asistencia a personas con impedimentos visuales'),
('Asistencia a personas con impedimentos sensoriales'),
('Asistencia a personas con impedimentos auditivos'),
('Asistencia a personas con episodios de convulsiones'),
('Asistencia a personas con ataques de ansiedad'),
('Asistencia a personas en sillas de ruedas'),
('Asistencia en piscinas'),
('Asistencia a niños con autismo'),
('Asistencia a personas de la tercera edad');

INSERT INTO lugar(lug_tipo,lug_nombre)VALUES('pais','VENEZUELA');
INSERT INTO lugar(lug_tipo,lug_nombre,lug_fk_lugar)VALUES('estado','DTTO. CAPITAL',1),('estado','ANZOATEGUI',1),('estado','APURE',1),('estado','ARAGUA',1),('estado','BARINAS',1),('estado','BOLIVAR',1),('estado','CARABOBO',1),('estado','COJEDES',1),('estado','FALCON',1),('estado','GUARICO',1),('estado','LARA',1),('estado','MERIDA',1),('estado','MIRANDA',1),('estado','MONAGAS',1),('estado','NUEVA ESPARTA',1),('estado','PORTUGUESA',1),('estado','SUCRE',1),('estado','TACHIRA',1),('estado','TRUJILLO',1),('estado','YARACUY',1),('estado','ZULIA',1),('estado','AMAZONAS',1),('estado','DELTA AMACURO',1),('estado','VARGAS',1);
INSERT INTO lugar(lug_tipo,lug_nombre,lug_fk_lugar)VALUES('municipio','LIBERTADOR', 2),('municipio','ANACO', 3),('municipio','ARAGUA', 3),('municipio','BOLIVAR', 3),('municipio','BRUZUAL', 3),('municipio','CAJIGAL', 3),('municipio','FREITES', 3),('municipio','INDEPENDENCIA', 3),('municipio','LIBERTAD', 3),('municipio','MIRANDA', 3),('municipio','MONAGAS', 3),('municipio','PEÑALVER', 3),('municipio','SIMON RODRIGUEZ', 3),('municipio','SOTILLO', 3),('municipio','GUANIPA', 3),('municipio','GUANTA', 3),('municipio','PIRITU', 3),('municipio','M.L/DIEGO BAUTISTA U', 3),('municipio','CARVAJAL', 3),('municipio','SANTA ANA', 3),('municipio','MC GREGOR', 3),('municipio','S JUAN CAPISTRANO', 3),('municipio','ACHAGUAS', 4),('municipio','MUÑOZ', 4),('municipio','PAEZ', 4),('municipio','PEDRO CAMEJO', 4),('municipio','ROMULO GALLEGOS', 4),('municipio','SAN FERNANDO', 4),('municipio','BIRUACA', 4),('municipio','GIRARDOT', 5),('municipio','SANTIAGO MARIÑO', 5),('municipio','JOSE FELIX RIVAS', 5),('municipio','SAN CASIMIRO', 5),('municipio','SAN SEBASTIAN', 5),('municipio','SUCRE', 5),('municipio','URDANETA', 5),('municipio','ZAMORA', 5),('municipio','LIBERTADOR', 5),('municipio','JOSE ANGEL LAMAS', 5),('municipio','BOLIVAR', 5),('municipio','SANTOS MICHELENA', 5),('municipio','MARIO B IRAGORRY', 5),('municipio','TOVAR', 5),('municipio','CAMATAGUA', 5),('municipio','JOSE R REVENGA', 5),('municipio','FRANCISCO LINARES A.', 5),('municipio','M.OCUMARE D LA COSTA', 5),('municipio','ARISMENDI', 6),('municipio','BARINAS', 6),('municipio','BOLIVAR', 6),('municipio','EZEQUIEL ZAMORA', 6),('municipio','OBISPOS', 6),('municipio','PEDRAZA', 6),('municipio','ROJAS', 6),('municipio','SOSA', 6),('municipio','ALBERTO ARVELO T', 6),('municipio','A JOSE DE SUCRE', 6),('municipio','CRUZ PAREDES', 6),('municipio','ANDRES E. BLANCO', 6),('municipio','CARONI', 7),('municipio','CEDEÑO', 7),('municipio','HERES', 7),('municipio','PIAR', 7),('municipio','ROSCIO', 7),('municipio','SUCRE', 7),('municipio','SIFONTES', 7),('municipio','RAUL LEONI', 7),('municipio','GRAN SABANA', 7),('municipio','EL CALLAO', 7),('municipio','PADRE PEDRO CHIEN', 7),('municipio','BEJUMA', 8),('municipio','CARLOS ARVELO', 8),('municipio','DIEGO IBARRA', 8),('municipio','GUACARA', 8),('municipio','MONTALBAN', 8),('municipio','JUAN JOSE MORA', 8),('municipio','PUERTO CABELLO', 8),('municipio','SAN JOAQUIN', 8),('municipio','VALENCIA', 8),('municipio','MIRANDA', 8),('municipio','LOS GUAYOS', 8),('municipio','NAGUANAGUA', 8),('municipio','SAN DIEGO', 8),('municipio','LIBERTADOR', 8),('municipio','ANZOATEGUI', 9),('municipio','FALCON', 9),('municipio','GIRARDOT', 9),('municipio','MP PAO SN J BAUTISTA', 9),('municipio','RICAURTE', 9),('municipio','SAN CARLOS', 9),('municipio','TINACO', 9),('municipio','LIMA BLANCO', 9),('municipio','ROMULO GALLEGOS', 9),('municipio','ACOSTA', 10),('municipio','BOLIVAR', 10),('municipio','BUCHIVACOA', 10),('municipio','CARIRUBANA', 10),('municipio','COLINA', 10),('municipio','DEMOCRACIA', 10),('municipio','FALCON', 10),('municipio','FEDERACION', 10),('municipio','MAUROA', 10),('municipio','MIRANDA', 10),('municipio','PETIT', 10),('municipio','SILVA', 10),('municipio','ZAMORA', 10),('municipio','DABAJURO', 10),('municipio','MONS. ITURRIZA', 10),('municipio','LOS TAQUES', 10),('municipio','PIRITU', 10),('municipio','UNION', 10),('municipio','SAN FRANCISCO', 10),('municipio','JACURA', 10),('municipio','CACIQUE MANAURE', 10),('municipio','PALMA SOLA', 10),('municipio','SUCRE', 10),('municipio','URUMACO', 10),('municipio','TOCOPERO', 10),('municipio','INFANTE', 11),('municipio','MELLADO', 11),('municipio','MIRANDA', 11),('municipio','MONAGAS', 11),('municipio','RIBAS', 11),('municipio','ROSCIO', 11),('municipio','ZARAZA', 11),('municipio','CAMAGUAN', 11),('municipio','S JOSE DE GUARIBE', 11),('municipio','LAS MERCEDES', 11),('municipio','EL SOCORRO', 11),('municipio','ORTIZ', 11),('municipio','S MARIA DE IPIRE', 11),('municipio','CHAGUARAMAS', 11),('municipio','SAN GERONIMO DE G', 11),('municipio','CRESPO', 12),('municipio','IRIBARREN', 12),('municipio','JIMENEZ', 12),('municipio','MORAN', 12),('municipio','PALAVECINO', 12),('municipio','TORRES', 12),('municipio','URDANETA', 12),('municipio','ANDRES E BLANCO', 12),('municipio','SIMON PLANAS', 12),('municipio','ALBERTO ADRIANI', 13),('municipio','ANDRES BELLO', 13),('municipio','ARZOBISPO CHACON', 13),('municipio','CAMPO ELIAS', 13),('municipio','GUARAQUE', 13),('municipio','JULIO CESAR SALAS', 13),('municipio','JUSTO BRICEÑO', 13),('municipio','LIBERTADOR', 13),('municipio','SANTOS MARQUINA', 13),('municipio','MIRANDA', 13),('municipio','ANTONIO PINTO S.', 13),('municipio','OB. RAMOS DE LORA', 13),('municipio','CARACCIOLO PARRA', 13),('municipio','CARDENAL QUINTERO', 13),('municipio','PUEBLO LLANO', 13),('municipio','RANGEL', 13),('municipio','RIVAS DAVILA', 13),('municipio','SUCRE', 13),('municipio','TOVAR', 13),('municipio','TULIO F CORDERO', 13),('municipio','PADRE NOGUERA', 13),('municipio','ARICAGUA', 13),('municipio','ZEA', 13),('municipio','ACEVEDO', 14),('municipio','BRION', 14),('municipio','GUAICAIPURO', 14),('municipio','INDEPENDENCIA', 14),('municipio','LANDER', 14),('municipio','PAEZ', 14),('municipio','PAZ CASTILLO', 14),('municipio','PLAZA', 14),('municipio','SUCRE', 14),('municipio','URDANETA', 14),('municipio','ZAMORA', 14),('municipio','CRISTOBAL ROJAS', 14),('municipio','LOS SALIAS', 14),('municipio','ANDRES BELLO', 14),('municipio','SIMON BOLIVAR', 14),('municipio','BARUTA', 14),('municipio','CARRIZAL', 14),('municipio','CHACAO', 14),('municipio','EL HATILLO', 14),('municipio','BUROZ', 14),('municipio','PEDRO GUAL', 14),('municipio','ACOSTA', 15),('municipio','BOLIVAR', 15),('municipio','CARIPE', 15),('municipio','CEDEÑO', 15),('municipio','EZEQUIEL ZAMORA', 15),('municipio','LIBERTADOR', 15),('municipio','MATURIN', 15),('municipio','PIAR', 15),('municipio','PUNCERES', 15),('municipio','SOTILLO', 15),('municipio','AGUASAY', 15),('municipio','SANTA BARBARA', 15),('municipio','URACOA', 15),('municipio','ARISMENDI', 16),('municipio','DIAZ', 16),('municipio','GOMEZ', 16),('municipio','MANEIRO', 16),('municipio','MARCANO', 16),('municipio','MARIÑO', 16),('municipio','PENIN. DE MACANAO', 16),('municipio','VILLALBA(I.COCHE)', 16),('municipio','TUBORES', 16),('municipio','ANTOLIN DEL CAMPO', 16),('municipio','GARCIA', 16),('municipio','ARAURE', 17),('municipio','ESTELLER', 17),('municipio','GUANARE', 17),('municipio','GUANARITO', 17),('municipio','OSPINO', 17),('municipio','PAEZ', 17),('municipio','SUCRE', 17),('municipio','TUREN', 17),('municipio','M.JOSE V DE UNDA', 17),('municipio','AGUA BLANCA', 17),('municipio','PAPELON', 17),('municipio','GENARO BOCONOITO', 17),('municipio','S RAFAEL DE ONOTO', 17),('municipio','SANTA ROSALIA', 17),('municipio','ARISMENDI', 18),('municipio','BENITEZ', 18),('municipio','BERMUDEZ', 18),('municipio','CAJIGAL', 18),('municipio','MARIÑO', 18),('municipio','MEJIA', 18),('municipio','MONTES', 18),('municipio','RIBERO', 18),('municipio','SUCRE', 18),('municipio','VALDEZ', 18),('municipio','ANDRES E BLANCO', 18),('municipio','LIBERTADOR', 18),('municipio','ANDRES MATA', 18),('municipio','BOLIVAR', 18),('municipio','CRUZ S ACOSTA', 18),('municipio','AYACUCHO', 19),('municipio','BOLIVAR', 19),('municipio','INDEPENDENCIA', 19),('municipio','CARDENAS', 19),('municipio','JAUREGUI', 19),('municipio','JUNIN', 19),('municipio','LOBATERA', 19),('municipio','SAN CRISTOBAL', 19),('municipio','URIBANTE', 19),('municipio','CORDOBA', 19),('municipio','GARCIA DE HEVIA', 19),('municipio','GUASIMOS', 19),('municipio','MICHELENA', 19),('municipio','LIBERTADOR', 19),('municipio','PANAMERICANO', 19),('municipio','PEDRO MARIA UREÑA', 19),('municipio','SUCRE', 19),('municipio','ANDRES BELLO', 19),('municipio','FERNANDEZ FEO', 19),('municipio','LIBERTAD', 19),('municipio','SAMUEL MALDONADO', 19),('municipio','SEBORUCO', 19),('municipio','ANTONIO ROMULO C', 19),('municipio','FCO DE MIRANDA', 19),('municipio','JOSE MARIA VARGA', 19),('municipio','RAFAEL URDANETA', 19),('municipio','SIMON RODRIGUEZ', 19),('municipio','TORBES', 19),('municipio','SAN JUDAS TADEO', 19),('municipio','RAFAEL RANGEL', 20),('municipio','BOCONO', 20),('municipio','CARACHE', 20),('municipio','ESCUQUE', 20),('municipio','TRUJILLO', 20),('municipio','URDANETA', 20),('municipio','VALERA', 20),('municipio','CANDELARIA', 20),('municipio','MIRANDA', 20),('municipio','MONTE CARMELO', 20),('municipio','MOTATAN', 20),('municipio','PAMPAN', 20),('municipio','S RAFAEL CARVAJAL', 20),('municipio','SUCRE', 20),('municipio','ANDRES BELLO', 20),('municipio','BOLIVAR', 20),('municipio','JOSE F M CAÑIZAL', 20),('municipio','JUAN V CAMPO ELI', 20),('municipio','LA CEIBA', 20),('municipio','PAMPANITO', 20),('municipio','BOLIVAR', 21),('municipio','BRUZUAL', 21),('municipio','NIRGUA', 21),('municipio','SAN FELIPE', 21),('municipio','SUCRE', 21),('municipio','URACHICHE', 21),('municipio','PEÑA', 21),('municipio','JOSE ANTONIO PAEZ', 21),('municipio','LA TRINIDAD', 21),('municipio','COCOROTE', 21),('municipio','INDEPENDENCIA', 21),('municipio','ARISTIDES BASTID', 21),('municipio','MANUEL MONGE', 21),('municipio','VEROES', 21),('municipio','BARALT', 22),('municipio','SANTA RITA', 22),('municipio','COLON', 22),('municipio','MARA', 22),('municipio','MARACAIBO', 22),('municipio','MIRANDA', 22),('municipio','PAEZ', 22),('municipio','MACHIQUES DE P', 22),('municipio','SUCRE', 22),('municipio','LA CAÑADA DE U.', 22),('municipio','LAGUNILLAS', 22),('municipio','CATATUMBO', 22),('municipio','M/ROSARIO DE PERIJA', 22),('municipio','CABIMAS', 22),('municipio','VALMORE RODRIGUEZ', 22),('municipio','JESUS E LOSSADA', 22),('municipio','ALMIRANTE P', 22),('municipio','SAN FRANCISCO', 22),('municipio','JESUS M SEMPRUN', 22),('municipio','FRANCISCO J PULG', 22),('municipio','SIMON BOLIVAR', 22),('municipio','ATURES', 23),('municipio','ATABAPO', 23),('municipio','MAROA', 23),('municipio','RIO NEGRO', 23),('municipio','AUTANA', 23),('municipio','MANAPIARE', 23),('municipio','ALTO ORINOCO', 23),('municipio','TUCUPITA', 24),('municipio','PEDERNALES', 24),('municipio','ANTONIO DIAZ', 24),('municipio','CASACOIMA', 24),('municipio','VARGAS', 25);
INSERT INTO lugar(lug_tipo,lug_nombre,lug_fk_lugar)VALUES('parroquia','ALTAGRACIA',26),('parroquia','CANDELARIA',26),('parroquia','CATEDRAL',26),('parroquia','LA PASTORA',26),('parroquia','SAN AGUSTIN',26),('parroquia','SAN JOSE',26),('parroquia','SAN JUAN',26),('parroquia','SANTA ROSALIA',26),('parroquia','SANTA TERESA',26),('parroquia','SUCRE',26),('parroquia','23 DE ENERO',26),('parroquia','ANTIMANO',26),('parroquia','EL RECREO',26),('parroquia','EL VALLE',26),('parroquia','LA VEGA',26),('parroquia','MACARAO',26),('parroquia','CARICUAO',26),('parroquia','EL JUNQUITO',26),('parroquia','COCHE',26),('parroquia','SAN PEDRO',26),('parroquia','SAN BERNARDINO',26),('parroquia','EL PARAISO',26),('parroquia','ANACO',27),('parroquia','SAN JOAQUIN',27),('parroquia','CM. ARAGUA DE BARCELONA',28),('parroquia','CACHIPO',28),('parroquia','EL CARMEN',29),('parroquia','SAN CRISTOBAL',29),('parroquia','BERGANTIN',29),('parroquia','CAIGUA',29),('parroquia','EL PILAR',29),('parroquia','NARICUAL',29),('parroquia','CM. CLARINES',30),('parroquia','GUANAPE',30),('parroquia','SABANA DE UCHIRE',30),('parroquia','CM. ONOTO',31),('parroquia','SAN PABLO',31),('parroquia','CM. CANTAURA',32),('parroquia','LIBERTADOR',32),('parroquia','SANTA ROSA',32),('parroquia','URICA',32),('parroquia','CM. SOLEDAD',33),('parroquia','MAMO',33),('parroquia','CM. SAN MATEO',34),('parroquia','EL CARITO',34),('parroquia','SANTA INES',34),('parroquia','CM. PARIAGUAN',35),('parroquia','ATAPIRIRE',35),('parroquia','BOCA DEL PAO',35),('parroquia','EL PAO',35),('parroquia','CM. MAPIRE',36),('parroquia','PIAR',36),('parroquia','SN DIEGO DE CABRUTICA',36),('parroquia','SANTA CLARA',36),('parroquia','UVERITO',36),('parroquia','ZUATA',36),('parroquia','CM. PUERTO PIRITU',37),('parroquia','SAN MIGUEL',37),('parroquia','SUCRE',37),('parroquia','CM. EL TIGRE',38),('parroquia','POZUELOS',39),('parroquia','CM PTO. LA CRUZ',39),('parroquia','CM. SAN JOSE DE GUANIPA',40),('parroquia','GUANTA',41),('parroquia','CHORRERON',41),('parroquia','PIRITU',42),('parroquia','SAN FRANCISCO',42),('parroquia','LECHERIAS',43),('parroquia','EL MORRO',43),('parroquia','VALLE GUANAPE',44),('parroquia','SANTA BARBARA',44),('parroquia','SANTA ANA',45),('parroquia','PUEBLO NUEVO',45),('parroquia','EL CHAPARRO',46),('parroquia','TOMAS ALFARO CALATRAVA',46),('parroquia','BOCA UCHIRE',47),('parroquia','BOCA DE CHAVEZ',47),('parroquia','ACHAGUAS',48),('parroquia','APURITO',48),('parroquia','EL YAGUAL',48),('parroquia','GUACHARA',48),('parroquia','MUCURITAS',48),('parroquia','QUESERAS DEL MEDIO',48),('parroquia','BRUZUAL',49),('parroquia','MANTECAL',49),('parroquia','QUINTERO',49),('parroquia','SAN VICENTE',49),('parroquia','RINCON HONDO',49),('parroquia','GUASDUALITO',50),('parroquia','ARAMENDI',50),('parroquia','EL AMPARO',50),('parroquia','SAN CAMILO',50),('parroquia','URDANETA',50),('parroquia','SAN JUAN DE PAYARA',51),('parroquia','CODAZZI',51),('parroquia','CUNAVICHE',51),('parroquia','ELORZA',52),('parroquia','LA TRINIDAD',52),('parroquia','SAN FERNANDO',53),('parroquia','PEÑALVER',53),('parroquia','EL RECREO',53),('parroquia','SN RAFAEL DE ATAMAICA',53),('parroquia','BIRUACA',54),('parroquia','CM. LAS DELICIAS',55),('parroquia','CHORONI',55),('parroquia','MADRE MA DE SAN JOSE',55),('parroquia','JOAQUIN CRESPO',55),('parroquia','PEDRO JOSE OVALLES',55),('parroquia','JOSE CASANOVA GODOY',55),('parroquia','ANDRES ELOY BLANCO',55),('parroquia','LOS TACARIGUAS',55),('parroquia','CM. TURMERO',56),('parroquia','SAMAN DE GUERE',56),('parroquia','ALFREDO PACHECO M',56),('parroquia','CHUAO',56),('parroquia','AREVALO APONTE',56),('parroquia','CM. LA VICTORIA',57),('parroquia','ZUATA',57),('parroquia','PAO DE ZARATE',57),('parroquia','CASTOR NIEVES RIOS',57),('parroquia','LAS GUACAMAYAS',57),('parroquia','CM. SAN CASIMIRO',58),('parroquia','VALLE MORIN',58),('parroquia','GUIRIPA',58),('parroquia','OLLAS DE CARAMACATE',58),('parroquia','CM. SAN SEBASTIAN',59),('parroquia','CM. CAGUA',60),('parroquia','BELLA VISTA',60),('parroquia','CM. BARBACOAS',61),('parroquia','SAN FRANCISCO DE CARA',61),('parroquia','TAGUAY',61),('parroquia','LAS PEÑITAS',61),('parroquia','CM. VILLA DE CURA',62),('parroquia','MAGDALENO',62),('parroquia','SAN FRANCISCO DE ASIS',62),('parroquia','VALLES DE TUCUTUNEMO',62),('parroquia','PQ AUGUSTO MIJARES',62),('parroquia','CM. PALO NEGRO',63),('parroquia','SAN MARTIN DE PORRES',63),('parroquia','CM. SANTA CRUZ',64),('parroquia','CM. SAN MATEO',65),('parroquia','CM. LAS TEJERIAS',66),('parroquia','TIARA',66),('parroquia','CM. EL LIMON',67),('parroquia','CA A DE AZUCAR',67),('parroquia','CM. COLONIA TOVAR',68),('parroquia','CM. CAMATAGUA',69),('parroquia','CARMEN DE CURA',69),('parroquia','CM. EL CONSEJO',70),('parroquia','CM. SANTA RITA',71),('parroquia','FRANCISCO DE MIRANDA',71),('parroquia','MONS FELICIANO G',71),('parroquia','OCUMARE DE LA COSTA',72),('parroquia','ARISMENDI',73),('parroquia','GUADARRAMA',73),('parroquia','LA UNION',73),('parroquia','SAN ANTONIO',73),('parroquia','ALFREDO A LARRIVA',74),('parroquia','BARINAS',74),('parroquia','SAN SILVESTRE',74),('parroquia','SANTA INES',74),('parroquia','SANTA LUCIA',74),('parroquia','TORUNOS',74),('parroquia','EL CARMEN',74),('parroquia','ROMULO BETANCOURT',74),('parroquia','CORAZON DE JESUS',74),('parroquia','RAMON I MENDEZ',74),('parroquia','ALTO BARINAS',74),('parroquia','MANUEL P FAJARDO',74),('parroquia','JUAN A RODRIGUEZ D',74),('parroquia','DOMINGA ORTIZ P',74),('parroquia','ALTAMIRA',75),('parroquia','BARINITAS',75),('parroquia','CALDERAS',75),('parroquia','SANTA BARBARA',76),('parroquia','JOSE IGNACIO DEL PUMAR',76),('parroquia','RAMON IGNACIO MENDEZ',76),('parroquia','PEDRO BRICEÑO MENDEZ',76),('parroquia','EL REAL',77),('parroquia','LA LUZ',77),('parroquia','OBISPOS',77),('parroquia','LOS GUASIMITOS',77),('parroquia','CIUDAD BOLIVIA',78),('parroquia','IGNACIO BRICEÑO',78),('parroquia','PAEZ',78),('parroquia','JOSE FELIX RIBAS',78),('parroquia','DOLORES',79),('parroquia','LIBERTAD',79),('parroquia','PALACIO FAJARDO',79),('parroquia','SANTA ROSA',79),('parroquia','CIUDAD DE NUTRIAS',80),('parroquia','EL REGALO',80),('parroquia','PUERTO DE NUTRIAS',80),('parroquia','SANTA CATALINA',80),('parroquia','RODRIGUEZ DOMINGUEZ',81),('parroquia','SABANETA',81),('parroquia','TICOPORO',82),('parroquia','NICOLAS PULIDO',82),('parroquia','ANDRES BELLO',82),('parroquia','BARRANCAS',83),('parroquia','EL SOCORRO',83),('parroquia','MASPARRITO',83),('parroquia','EL CANTON',84),('parroquia','SANTA CRUZ DE GUACAS',84),('parroquia','PUERTO VIVAS',84),('parroquia','SIMON BOLIVAR',85),('parroquia','ONCE DE ABRIL',85),('parroquia','VISTA AL SOL',85),('parroquia','CHIRICA',85),('parroquia','DALLA COSTA',85),('parroquia','CACHAMAY',85),('parroquia','UNIVERSIDAD',85),('parroquia','UNARE',85),('parroquia','YOCOIMA',85),('parroquia','POZO VERDE',85),('parroquia','CM. CAICARA DEL ORINOCO',86),('parroquia','ASCENSION FARRERAS',86),('parroquia','ALTAGRACIA',86),('parroquia','LA URBANA',86),('parroquia','GUANIAMO',86),('parroquia','PIJIGUAOS',86),('parroquia','CATEDRAL',87),('parroquia','AGUA SALADA',87),('parroquia','LA SABANITA',87),('parroquia','VISTA HERMOSA',87),('parroquia','MARHUANTA',87),('parroquia','JOSE ANTONIO PAEZ',87),('parroquia','ORINOCO',87),('parroquia','PANAPANA',87),('parroquia','ZEA',87),('parroquia','CM. UPATA',88),('parroquia','ANDRES ELOY BLANCO',88),('parroquia','PEDRO COVA',88),('parroquia','CM. GUASIPATI',89),('parroquia','SALOM',89),('parroquia','CM. MARIPA',90),('parroquia','ARIPAO',90),('parroquia','LAS MAJADAS',90),('parroquia','MOITACO',90),('parroquia','GUARATARO',90),('parroquia','CM. TUMEREMO',91),('parroquia','DALLA COSTA',91),('parroquia','SAN ISIDRO',91),('parroquia','CM. CIUDAD PIAR',92),('parroquia','SAN FRANCISCO',92),('parroquia','BARCELONETA',92),('parroquia','SANTA BARBARA',92),('parroquia','CM. SANTA ELENA DE UAIREN',93),('parroquia','IKABARU',93),('parroquia','CM. EL CALLAO',94),('parroquia','CM. EL PALMAR',95),('parroquia','BEJUMA',96),('parroquia','CANOABO',96),('parroquia','SIMON BOLIVAR',96),('parroquia','GUIGUE',97),('parroquia','BELEN',97),('parroquia','TACARIGUA',97),('parroquia','MARIARA',98),('parroquia','AGUAS CALIENTES',98),('parroquia','GUACARA',99),('parroquia','CIUDAD ALIANZA',99),('parroquia','YAGUA',99),('parroquia','MONTALBAN',100),('parroquia','MORON',101),('parroquia','URAMA',101),('parroquia','DEMOCRACIA',102),('parroquia','FRATERNIDAD',102),('parroquia','GOAIGOAZA',102),('parroquia','JUAN JOSE FLORES',102),('parroquia','BARTOLOME SALOM',102),('parroquia','UNION',102),('parroquia','BORBURATA',102),('parroquia','PATANEMO',102),('parroquia','SAN JOAQUIN',103),('parroquia','CANDELARIA',104),('parroquia','CATEDRAL',104),('parroquia','EL SOCORRO',104),('parroquia','MIGUEL PEÑA',104),('parroquia','SAN BLAS',104),('parroquia','SAN JOSE',104),('parroquia','SANTA ROSA',104),('parroquia','RAFAEL URDANETA',104),('parroquia','NEGRO PRIMERO',104),('parroquia','MIRANDA',105),('parroquia','U LOS GUAYOS',106),('parroquia','NAGUANAGUA',107),('parroquia','URB SAN DIEGO',108),('parroquia','U TOCUYITO',109),('parroquia','U INDEPENDENCIA',109),('parroquia','COJEDES',110),('parroquia','JUAN DE MATA SUAREZ',110),('parroquia','TINAQUILLO',111),('parroquia','EL BAUL',112),('parroquia','SUCRE',112),('parroquia','EL PAO',113),('parroquia','LIBERTAD DE COJEDES',114),('parroquia','EL AMPARO',114),('parroquia','SAN CARLOS DE AUSTRIA',115),('parroquia','JUAN ANGEL BRAVO',115),('parroquia','MANUEL MANRIQUE',115),('parroquia','GRL/JEFE JOSE L SILVA',116),('parroquia','MACAPO',117),('parroquia','LA AGUADITA',117),('parroquia','ROMULO GALLEGOS',118),('parroquia','SAN JUAN DE LOS CAYOS',119),('parroquia','CAPADARE',119),('parroquia','LA PASTORA',119),('parroquia','LIBERTADOR',119),('parroquia','SAN LUIS',120),('parroquia','ARACUA',120),('parroquia','LA PEÑA',120),('parroquia','CAPATARIDA',121),('parroquia','BOROJO',121),('parroquia','SEQUE',121),('parroquia','ZAZARIDA',121),('parroquia','BARIRO',121),('parroquia','GUAJIRO',121),('parroquia','NORTE',122),('parroquia','CARIRUBANA',122),('parroquia','PUNTA CARDON',122),('parroquia','SANTA ANA',122),('parroquia','LA VELA DE CORO',123),('parroquia','ACURIGUA',123),('parroquia','GUAIBACOA',123),('parroquia','MACORUCA',123),('parroquia','LAS CALDERAS',123),('parroquia','PEDREGAL',124),('parroquia','AGUA CLARA',124),('parroquia','AVARIA',124),('parroquia','PIEDRA GRANDE',124),('parroquia','PURURECHE',124),('parroquia','PUEBLO NUEVO',125),('parroquia','ADICORA',125),('parroquia','BARAIVED',125),('parroquia','BUENA VISTA',125),('parroquia','JADACAQUIVA',125),('parroquia','MORUY',125),('parroquia','EL VINCULO',125),('parroquia','EL HATO',125),('parroquia','ADAURE',125),('parroquia','CHURUGUARA',126),('parroquia','AGUA LARGA',126),('parroquia','INDEPENDENCIA',126),('parroquia','MAPARARI',126),('parroquia','EL PAUJI',126),('parroquia','MENE DE MAUROA',127),('parroquia','CASIGUA',127),('parroquia','SAN FELIX',127),('parroquia','SAN ANTONIO',128),('parroquia','SAN GABRIEL',128),('parroquia','SANTA ANA',128),('parroquia','GUZMAN GUILLERMO',128),('parroquia','MITARE',128),('parroquia','SABANETA',128),('parroquia','RIO SECO',128),('parroquia','CABURE',129),('parroquia','CURIMAGUA',129),('parroquia','COLINA',129),('parroquia','TUCACAS',130),('parroquia','BOCA DE AROA',130),('parroquia','PUERTO CUMAREBO',131),('parroquia','LA CIENAGA',131),('parroquia','LA SOLEDAD',131),('parroquia','PUEBLO CUMAREBO',131),('parroquia','ZAZARIDA',131),('parroquia','CM. DABAJURO',132),('parroquia','CHICHIRIVICHE',133),('parroquia','BOCA DE TOCUYO',133),('parroquia','TOCUYO DE LA COSTA',133),('parroquia','LOS TAQUES',134),('parroquia','JUDIBANA',134),('parroquia','PIRITU',135),('parroquia','SAN JOSE DE LA COSTA',135),('parroquia','STA.CRUZ DE BUCARAL',136),('parroquia','EL CHARAL',136),('parroquia','LAS VEGAS DEL TUY',136),('parroquia','CM. MIRIMIRE',137),('parroquia','JACURA',138),('parroquia','AGUA LINDA',138),('parroquia','ARAURIMA',138),('parroquia','CM. YARACAL',139),('parroquia','CM. PALMA SOLA',140),('parroquia','SUCRE',141),('parroquia','PECAYA',141),('parroquia','URUMACO',142),('parroquia','BRUZUAL',142),('parroquia','CM. TOCOPERO',143),('parroquia','VALLE DE LA PASCUA',144),('parroquia','ESPINO',144),('parroquia','EL SOMBRERO',145),('parroquia','SOSA',145),('parroquia','CALABOZO',146),('parroquia','EL CALVARIO',146),('parroquia','EL RASTRO',146),('parroquia','GUARDATINAJAS',146),('parroquia','ALTAGRACIA DE ORITUCO',147),('parroquia','LEZAMA',147),('parroquia','LIBERTAD DE ORITUCO',147),('parroquia','SAN FCO DE MACAIRA',147),('parroquia','SAN RAFAEL DE ORITUCO',147),('parroquia','SOUBLETTE',147),('parroquia','PASO REAL DE MACAIRA',147),('parroquia','TUCUPIDO',148),('parroquia','SAN RAFAEL DE LAYA',148),('parroquia','SAN JUAN DE LOS MORROS',149),('parroquia','PARAPARA',149),('parroquia','CANTAGALLO',149),('parroquia','ZARAZA',150),('parroquia','SAN JOSE DE UNARE',150),('parroquia','CAMAGUAN',151),('parroquia','PUERTO MIRANDA',151),('parroquia','UVERITO',151),('parroquia','SAN JOSE DE GUARIBE',152),('parroquia','LAS MERCEDES',153),('parroquia','STA RITA DE MANAPIRE',153),('parroquia','CABRUTA',153),('parroquia','EL SOCORRO',154),('parroquia','ORTIZ',155),('parroquia','SAN FCO. DE TIZNADOS',155),('parroquia','SAN JOSE DE TIZNADOS',155),('parroquia','S LORENZO DE TIZNADOS',155),('parroquia','SANTA MARIA DE IPIRE',156),('parroquia','ALTAMIRA',156),('parroquia','CHAGUARAMAS',157),('parroquia','GUAYABAL',158),('parroquia','CAZORLA',158),('parroquia','FREITEZ',159),('parroquia','JOSE MARIA BLANCO',159),('parroquia','CATEDRAL',160),('parroquia','LA CONCEPCION',160),('parroquia','SANTA ROSA',160),('parroquia','UNION',160),('parroquia','EL CUJI',160),('parroquia','TAMACA',160),('parroquia','JUAN DE VILLEGAS',160),('parroquia','AGUEDO F. ALVARADO',160),('parroquia','BUENA VISTA',160),('parroquia','JUAREZ',160),('parroquia','JUAN B RODRIGUEZ',161),('parroquia','DIEGO DE LOZADA',161),('parroquia','SAN MIGUEL',161),('parroquia','CUARA',161),('parroquia','PARAISO DE SAN JOSE',161),('parroquia','TINTORERO',161),('parroquia','JOSE BERNARDO DORANTE',161),('parroquia','CRNEL. MARIANO PERAZA',161),('parroquia','BOLIVAR',162),('parroquia','ANZOATEGUI',162),('parroquia','GUARICO',162),('parroquia','HUMOCARO ALTO',162),('parroquia','HUMOCARO BAJO',162),('parroquia','MORAN',162),('parroquia','HILARIO LUNA Y LUNA',162),('parroquia','LA CANDELARIA',162),('parroquia','CABUDARE',163),('parroquia','JOSE G. BASTIDAS',163),('parroquia','AGUA VIVA',163),('parroquia','TRINIDAD SAMUEL',164),('parroquia','ANTONIO DIAZ',164),('parroquia','CAMACARO',164),('parroquia','CASTAÑEDA',164),('parroquia','CHIQUINQUIRA',164),('parroquia','ESPINOZA LOS MONTEROS',164),('parroquia','LARA',164),('parroquia','MANUEL MORILLO',164),('parroquia','MONTES DE OCA',164),('parroquia','TORRES',164),('parroquia','EL BLANCO',164),('parroquia','MONTA A VERDE',164),('parroquia','HERIBERTO ARROYO',164),('parroquia','LAS MERCEDES',164),('parroquia','CECILIO ZUBILLAGA',164),('parroquia','REYES VARGAS',164),('parroquia','ALTAGRACIA',164),('parroquia','SIQUISIQUE',165),('parroquia','SAN MIGUEL',165),('parroquia','XAGUAS',165),('parroquia','MOROTURO',165),('parroquia','PIO TAMAYO',166),('parroquia','YACAMBU',166),('parroquia','QBDA. HONDA DE GUACHE',166),('parroquia','SARARE',167),('parroquia','GUSTAVO VEGAS LEON',167),('parroquia','BURIA',167),('parroquia','GABRIEL PICON G.',168),('parroquia','HECTOR AMABLE MORA',168),('parroquia','JOSE NUCETE SARDI',168),('parroquia','PULIDO MENDEZ',168),('parroquia','PTE. ROMULO GALLEGOS',168),('parroquia','PRESIDENTE BETANCOURT',168),('parroquia','PRESIDENTE PAEZ',168),('parroquia','CM. LA AZULITA',169),('parroquia','CM. CANAGUA',170),('parroquia','CAPURI',170),('parroquia','CHACANTA',170),('parroquia','EL MOLINO',170),('parroquia','GUAIMARAL',170),('parroquia','MUCUTUY',170),('parroquia','MUCUCHACHI',170),('parroquia','ACEQUIAS',171),('parroquia','JAJI',171),('parroquia','LA MESA',171),('parroquia','SAN JOSE',171),('parroquia','MONTALBAN',171),('parroquia','MATRIZ',171),('parroquia','FERNANDEZ PEÑA',171),('parroquia','CM. GUARAQUE',172),('parroquia','MESA DE QUINTERO',172),('parroquia','RIO NEGRO',172),('parroquia','CM. ARAPUEY',173),('parroquia','PALMIRA',173),('parroquia','CM. TORONDOY',174),('parroquia','SAN CRISTOBAL DE T',174),('parroquia','ARIAS',175),('parroquia','SAGRARIO',175),('parroquia','MILLA',175),('parroquia','EL LLANO',175),('parroquia','JUAN RODRIGUEZ SUAREZ',175),('parroquia','JACINTO PLAZA',175),('parroquia','DOMINGO PEÑA',175),('parroquia','GONZALO PICON FEBRES',175),('parroquia','OSUNA RODRIGUEZ',175),('parroquia','LASSO DE LA VEGA',175),('parroquia','CARACCIOLO PARRA P',175),('parroquia','MARIANO PICON SALAS',175),('parroquia','ANTONIO SPINETTI DINI',175),('parroquia','EL MORRO',175),('parroquia','LOS NEVADOS',175),('parroquia','CM. TABAY',176),('parroquia','CM. TIMOTES',177),('parroquia','ANDRES ELOY BLANCO',177),('parroquia','PIÑANGO',177),('parroquia','LA VENTA',177),('parroquia','CM. STA CRUZ DE MORA',178),('parroquia','MESA BOLIVAR',178),('parroquia','MESA DE LAS PALMAS',178),('parroquia','CM. STA ELENA DE ARENALES',179),('parroquia','ELOY PAREDES',179),('parroquia','PQ R DE ALCAZAR',179),('parroquia','CM. TUCANI',180),('parroquia','FLORENCIO RAMIREZ',180),('parroquia','CM. SANTO DOMINGO',181),('parroquia','LAS PIEDRAS',181),('parroquia','CM. PUEBLO LLANO',182),('parroquia','CM. MUCUCHIES',183),('parroquia','MUCURUBA',183),('parroquia','SAN RAFAEL',183),('parroquia','CACUTE',183),('parroquia','LA TOMA',183),('parroquia','CM. BAILADORES',184),('parroquia','GERONIMO MALDONADO',184),('parroquia','CM. LAGUNILLAS',185),('parroquia','CHIGUARA',185),('parroquia','ESTANQUES',185),('parroquia','SAN JUAN',185),('parroquia','PUEBLO NUEVO DEL SUR',185),('parroquia','LA TRAMPA',185),('parroquia','EL LLANO',186),('parroquia','TOVAR',186),('parroquia','EL AMPARO',186),('parroquia','SAN FRANCISCO',186),('parroquia','CM. NUEVA BOLIVIA',187),('parroquia','INDEPENDENCIA',187),('parroquia','MARIA C PALACIOS',187),('parroquia','SANTA APOLONIA',187),('parroquia','CM. STA MARIA DE CAPARO',188),('parroquia','CM. ARICAGUA',189),('parroquia','SAN ANTONIO',189),('parroquia','CM. ZEA',190),('parroquia','CAÑO EL TIGRE',190),('parroquia','CAUCAGUA',191),('parroquia','ARAGUITA',191),('parroquia','AREVALO GONZALEZ',191),('parroquia','CAPAYA',191),('parroquia','PANAQUIRE',191),('parroquia','RIBAS',191),('parroquia','EL CAFE',191),('parroquia','MARIZAPA',191),('parroquia','HIGUEROTE',192),('parroquia','CURIEPE',192),('parroquia','TACARIGUA',192),('parroquia','LOS TEQUES',193),('parroquia','CECILIO ACOSTA',193),('parroquia','PARACOTOS',193),('parroquia','SAN PEDRO',193),('parroquia','TACATA',193),('parroquia','EL JARILLO',193),('parroquia','ALTAGRACIA DE LA M',193),('parroquia','STA TERESA DEL TUY',194),('parroquia','EL CARTANAL',194),('parroquia','OCUMARE DEL TUY',195),('parroquia','LA DEMOCRACIA',195),('parroquia','SANTA BARBARA',195),('parroquia','RIO CHICO',196),('parroquia','EL GUAPO',196),('parroquia','TACARIGUA DE LA LAGUNA',196),('parroquia','PAPARO',196),('parroquia','SN FERNANDO DEL GUAPO',196),('parroquia','SANTA LUCIA',197),('parroquia','GUARENAS',198),('parroquia','PETARE',199),('parroquia','LEONCIO MARTINEZ',199),('parroquia','CAUCAGUITA',199),('parroquia','FILAS DE MARICHES',199),('parroquia','LA DOLORITA',199),('parroquia','CUA',200),('parroquia','NUEVA CUA',200),('parroquia','GUATIRE',201),('parroquia','BOLIVAR',201),('parroquia','CHARALLAVE',202),('parroquia','LAS BRISAS',202),('parroquia','SAN ANTONIO LOS ALTOS',203),('parroquia','SAN JOSE DE BARLOVENTO',204),('parroquia','CUMBO',204),('parroquia','SAN FCO DE YARE',205),('parroquia','S ANTONIO DE YARE',205),('parroquia','BARUTA',206),('parroquia','EL CAFETAL',206),('parroquia','LAS MINAS DE BARUTA',206),('parroquia','CARRIZAL',207),('parroquia','CHACAO',208),('parroquia','EL HATILLO',209),('parroquia','MAMPORAL',210),('parroquia','CUPIRA',211),('parroquia','MACHURUCUTO',211),('parroquia','CM. SAN ANTONIO',212),('parroquia','SAN FRANCISCO',212),('parroquia','CM. CARIPITO',213),('parroquia','CM. CARIPE',214),('parroquia','TERESEN',214),('parroquia','EL GUACHARO',214),('parroquia','SAN AGUSTIN',214),('parroquia','LA GUANOTA',214),('parroquia','SABANA DE PIEDRA',214),('parroquia','CM. CAICARA',215),('parroquia','AREO',215),('parroquia','SAN FELIX',215),('parroquia','VIENTO FRESCO',215),('parroquia','CM. PUNTA DE MATA',216),('parroquia','EL TEJERO',216),('parroquia','CM. TEMBLADOR',217),('parroquia','TABASCA',217),('parroquia','LAS ALHUACAS',217),('parroquia','CHAGUARAMAS',217),('parroquia','EL FURRIAL',218),('parroquia','JUSEPIN',218),('parroquia','EL COROZO',218),('parroquia','SAN VICENTE',218),('parroquia','LA PICA',218),('parroquia','ALTO DE LOS GODOS',218),('parroquia','BOQUERON',218),('parroquia','LAS COCUIZAS',218),('parroquia','SANTA CRUZ',218),('parroquia','SAN SIMON',218),('parroquia','CM. ARAGUA',219),('parroquia','CHAGUARAMAL',219),('parroquia','GUANAGUANA',219),('parroquia','APARICIO',219),('parroquia','TAGUAYA',219),('parroquia','EL PINTO',219),('parroquia','LA TOSCANA',219),('parroquia','CM. QUIRIQUIRE',220),('parroquia','CACHIPO',220),('parroquia','CM. BARRANCAS',221),('parroquia','LOS BARRANCOS DE FAJARDO',221),('parroquia','CM. AGUASAY',222),('parroquia','CM. SANTA BARBARA',223),('parroquia','CM. URACOA',224),('parroquia','CM. LA ASUNCION',225),('parroquia','CM. SAN JUAN BAUTISTA',226),('parroquia','ZABALA',226),('parroquia','CM. SANTA ANA',227),('parroquia','GUEVARA',227),('parroquia','MATASIETE',227),('parroquia','BOLIVAR',227),('parroquia','SUCRE',227),('parroquia','CM. PAMPATAR',228),('parroquia','AGUIRRE',228),('parroquia','CM. JUAN GRIEGO',229),('parroquia','ADRIAN',229),('parroquia','CM. PORLAMAR',230),('parroquia','CM. BOCA DEL RIO',231),('parroquia','SAN FRANCISCO',231),('parroquia','CM. SAN PEDRO DE COCHE',232),('parroquia','VICENTE FUENTES',232),('parroquia','CM. PUNTA DE PIEDRAS',233),('parroquia','LOS BARALES',233),('parroquia','CM.LA PLAZA DE PARAGUACHI',234),('parroquia','CM. VALLE ESP SANTO',235),('parroquia','FRANCISCO FAJARDO',235),('parroquia','CM. ARAURE',236),('parroquia','RIO ACARIGUA',236),('parroquia','CM. PIRITU',237),('parroquia','UVERAL',237),('parroquia','CM. GUANARE',238),('parroquia','CORDOBA',238),('parroquia','SAN JUAN GUANAGUANARE',238),('parroquia','VIRGEN DE LA COROMOTO',238),('parroquia','SAN JOSE DE LA MONTAÑA',238),('parroquia','CM. GUANARITO',239),('parroquia','TRINIDAD DE LA CAPILLA',239),('parroquia','DIVINA PASTORA',239),('parroquia','CM. OSPINO',240),('parroquia','APARICION',240),('parroquia','LA ESTACION',240),('parroquia','CM. ACARIGUA',241),('parroquia','PAYARA',241),('parroquia','PIMPINELA',241),('parroquia','RAMON PERAZA',241),('parroquia','CM. BISCUCUY',242),('parroquia','CONCEPCION',242),('parroquia','SAN RAFAEL PALO ALZADO',242),('parroquia','UVENCIO A VELASQUEZ',242),('parroquia','SAN JOSE DE SAGUAZ',242),('parroquia','VILLA ROSA',242),('parroquia','CM. VILLA BRUZUAL',243),('parroquia','CANELONES',243),('parroquia','SANTA CRUZ',243),('parroquia','SAN ISIDRO LABRADOR',243),('parroquia','CM. CHABASQUEN',244),('parroquia','PEÑA BLANCA',244),('parroquia','CM. AGUA BLANCA',245),('parroquia','CM. PAPELON',246),('parroquia','CAÑO DELGADITO',246),('parroquia','CM. BOCONOITO',247),('parroquia','ANTOLIN TOVAR AQUINO',247),('parroquia','CM. SAN RAFAEL DE ONOTO',248),('parroquia','SANTA FE',248),('parroquia','THERMO MORLES',248),('parroquia','CM. EL PLAYON',249),('parroquia','FLORIDA',249),('parroquia','RIO CARIBE',250),('parroquia','SAN JUAN GALDONAS',250),('parroquia','PUERTO SANTO',250),('parroquia','EL MORRO DE PTO SANTO',250),('parroquia','ANTONIO JOSE DE SUCRE',250),('parroquia','EL PILAR',251),('parroquia','EL RINCON',251),('parroquia','GUARAUNOS',251),('parroquia','TUNAPUICITO',251),('parroquia','UNION',251),('parroquia','GRAL FCO. A VASQUEZ',251),('parroquia','SANTA CATALINA',252),('parroquia','SANTA ROSA',252),('parroquia','SANTA TERESA',252),('parroquia','BOLIVAR',252),('parroquia','MACARAPANA',252),('parroquia','YAGUARAPARO',253),('parroquia','LIBERTAD',253),('parroquia','PAUJIL',253),('parroquia','IRAPA',254),('parroquia','CAMPO CLARO',254),('parroquia','SORO',254),('parroquia','SAN ANTONIO DE IRAPA',254),('parroquia','MARABAL',254),('parroquia','CM. SAN ANT DEL GOLFO',255),('parroquia','CUMANACOA',256),('parroquia','ARENAS',256),('parroquia','ARICAGUA',256),('parroquia','COCOLLAR',256),('parroquia','SAN FERNANDO',256),('parroquia','SAN LORENZO',256),('parroquia','CARIACO',257),('parroquia','CATUARO',257),('parroquia','RENDON',257),('parroquia','SANTA CRUZ',257),('parroquia','SANTA MARIA',257),('parroquia','ALTAGRACIA',258),('parroquia','AYACUCHO',258),('parroquia','SANTA INES',258),('parroquia','VALENTIN VALIENTE',258),('parroquia','SAN JUAN',258),('parroquia','GRAN MARISCAL',258),('parroquia','RAUL LEONI',258),('parroquia','GUIRIA',259),('parroquia','CRISTOBAL COLON',259),('parroquia','PUNTA DE PIEDRA',259),('parroquia','BIDEAU',259),('parroquia','MARIÑO',260),('parroquia','ROMULO GALLEGOS',260),('parroquia','TUNAPUY',261),('parroquia','CAMPO ELIAS',261),('parroquia','SAN JOSE DE AREOCUAR',262),('parroquia','TAVERA ACOSTA',262),('parroquia','CM. MARIGUITAR',263),('parroquia','ARAYA',264),('parroquia','MANICUARE',264),('parroquia','CHACOPATA',264),('parroquia','CM. COLON',265),('parroquia','RIVAS BERTI',265),('parroquia','SAN PEDRO DEL RIO',265),('parroquia','CM. SAN ANT DEL TACHIRA',266),('parroquia','PALOTAL',266),('parroquia','JUAN VICENTE GOMEZ',266),('parroquia','ISAIAS MEDINA ANGARIT',266),('parroquia','CM. CAPACHO NUEVO',267),('parroquia','JUAN GERMAN ROSCIO',267),('parroquia','ROMAN CARDENAS',267),('parroquia','CM. TARIBA',268),('parroquia','LA FLORIDA',268),('parroquia','AMENODORO RANGEL LAMU',268),('parroquia','CM. LA GRITA',269),('parroquia','EMILIO C. GUERRERO',269),('parroquia','MONS. MIGUEL A SALAS',269),('parroquia','CM. RUBIO',270),('parroquia','BRAMON',270),('parroquia','LA PETROLEA',270),('parroquia','QUINIMARI',270),('parroquia','CM. LOBATERA',271),('parroquia','CONSTITUCION',271),('parroquia','LA CONCORDIA',272),('parroquia','PEDRO MARIA MORANTES',272),('parroquia','SN JUAN BAUTISTA',272),('parroquia','SAN SEBASTIAN',272),('parroquia','DR. FCO. ROMERO LOBO',272),('parroquia','CM. PREGONERO',273),('parroquia','CARDENAS',273),('parroquia','POTOSI',273),('parroquia','JUAN PABLO PEÑALOZA',273),('parroquia','CM. STA. ANA  DEL TACHIRA',274),('parroquia','CM. LA FRIA',275),('parroquia','BOCA DE GRITA',275),('parroquia','JOSE ANTONIO PAEZ',275),('parroquia','CM. PALMIRA',276),('parroquia','CM. MICHELENA',277),('parroquia','CM. ABEJALES',278),('parroquia','SAN JOAQUIN DE NAVAY',278),('parroquia','DORADAS',278),('parroquia','EMETERIO OCHOA',278),('parroquia','CM. COLONCITO',279),('parroquia','LA PALMITA',279),('parroquia','CM. UREÑA',280),('parroquia','NUEVA ARCADIA',280),('parroquia','CM. QUENIQUEA',281),('parroquia','SAN PABLO',281),('parroquia','ELEAZAR LOPEZ CONTRERA',281),('parroquia','CM. CORDERO',282),('parroquia','CM.SAN RAFAEL DEL PINAL',283),('parroquia','SANTO DOMINGO',283),('parroquia','ALBERTO ADRIANI',283),('parroquia','CM. CAPACHO VIEJO',284),('parroquia','CIPRIANO CASTRO',284),('parroquia','MANUEL FELIPE RUGELES',284),('parroquia','CM. LA TENDIDA',285),('parroquia','BOCONO',285),('parroquia','HERNANDEZ',285),('parroquia','CM. SEBORUCO',286),('parroquia','CM. LAS MESAS',287),('parroquia','CM. SAN JOSE DE BOLIVAR',288),('parroquia','CM. EL COBRE',289),('parroquia','CM. DELICIAS',290),('parroquia','CM. SAN SIMON',291),('parroquia','CM. SAN JOSECITO',292),('parroquia','CM. UMUQUENA',293),('parroquia','BETIJOQUE',294),('parroquia','JOSE G HERNANDEZ',294),('parroquia','LA PUEBLITA',294),('parroquia','EL CEDRO',294),('parroquia','BOCONO',295),('parroquia','EL CARMEN',295),('parroquia','MOSQUEY',295),('parroquia','AYACUCHO',295),('parroquia','BURBUSAY',295),('parroquia','GENERAL RIVAS',295),('parroquia','MONSEÑOR JAUREGUI',295),('parroquia','RAFAEL RANGEL',295),('parroquia','SAN JOSE',295),('parroquia','SAN MIGUEL',295),('parroquia','GUARAMACAL',295),('parroquia','LA VEGA DE GUARAMACAL',295),('parroquia','CARACHE',296),('parroquia','LA CONCEPCION',296),('parroquia','CUICAS',296),('parroquia','PANAMERICANA',296),('parroquia','SANTA CRUZ',296),('parroquia','ESCUQUE',297),('parroquia','SABANA LIBRE',297),('parroquia','LA UNION',297),('parroquia','SANTA RITA',297),('parroquia','CRISTOBAL MENDOZA',298),('parroquia','CHIQUINQUIRA',298),('parroquia','MATRIZ',298),('parroquia','MONSEÑOR CARRILLO',298),('parroquia','CRUZ CARRILLO',298),('parroquia','ANDRES LINARES',298),('parroquia','TRES ESQUINAS',298),('parroquia','LA QUEBRADA',299),('parroquia','JAJO',299),('parroquia','LA MESA',299),('parroquia','SANTIAGO',299),('parroquia','CABIMBU',299),('parroquia','TUÑAME',299),('parroquia','MERCEDES DIAZ',300),('parroquia','JUAN IGNACIO MONTILLA',300),('parroquia','LA BEATRIZ',300),('parroquia','MENDOZA',300),('parroquia','LA PUERTA',300),('parroquia','SAN LUIS',300),('parroquia','CHEJENDE',301),('parroquia','CARRILLO',301),('parroquia','CEGARRA',301),('parroquia','BOLIVIA',301),('parroquia','MANUEL SALVADOR ULLOA',301),('parroquia','SAN JOSE',301),('parroquia','ARNOLDO GABALDON',301),('parroquia','EL DIVIDIVE',302),('parroquia','AGUA CALIENTE',302),('parroquia','EL CENIZO',302),('parroquia','AGUA SANTA',302),('parroquia','VALERITA',302),('parroquia','MONTE CARMELO',303),('parroquia','BUENA VISTA',303),('parroquia','STA MARIA DEL HORCON',303),('parroquia','MOTATAN',304),('parroquia','EL BAÑO',304),('parroquia','JALISCO',304),('parroquia','PAMPAN',305),('parroquia','SANTA ANA',305),('parroquia','LA PAZ',305),('parroquia','FLOR DE PATRIA',305),('parroquia','CARVAJAL',306),('parroquia','ANTONIO N BRICEÑO',306),('parroquia','CAMPO ALEGRE',306),('parroquia','JOSE LEONARDO SUAREZ',306),('parroquia','SABANA DE MENDOZA',307),('parroquia','JUNIN',307),('parroquia','VALMORE RODRIGUEZ',307),('parroquia','EL PARAISO',307),('parroquia','SANTA ISABEL',308),('parroquia','ARAGUANEY',308),('parroquia','EL JAGUITO',308),('parroquia','LA ESPERANZA',308),('parroquia','SABANA GRANDE',309),('parroquia','CHEREGUE',309),('parroquia','GRANADOS',309),('parroquia','EL SOCORRO',310),('parroquia','LOS CAPRICHOS',310),('parroquia','ANTONIO JOSE DE SUCRE',310),('parroquia','CAMPO ELIAS',311),('parroquia','ARNOLDO GABALDON',311),('parroquia','SANTA APOLONIA',312),('parroquia','LA CEIBA',312),('parroquia','EL PROGRESO',312),('parroquia','TRES DE FEBRERO',312),('parroquia','PAMPANITO',313),('parroquia','PAMPANITO II',313),('parroquia','LA CONCEPCION',313),('parroquia','CM. AROA',314),('parroquia','CM. CHIVACOA',315),('parroquia','CAMPO ELIAS',315),('parroquia','CM. NIRGUA',316),('parroquia','SALOM',316),('parroquia','TEMERLA',316),('parroquia','CM. SAN FELIPE',317),('parroquia','ALBARICO',317),('parroquia','SAN JAVIER',317),('parroquia','CM. GUAMA',318),('parroquia','CM. URACHICHE',319),('parroquia','CM. YARITAGUA',320),('parroquia','SAN ANDRES',320),('parroquia','CM. SABANA DE PARRA',321),('parroquia','CM. BORAURE',322),('parroquia','CM. COCOROTE',323),('parroquia','CM. INDEPENDENCIA',324),('parroquia','CM. SAN PABLO',325),('parroquia','CM. YUMARE',326),('parroquia','CM. FARRIAR',327),('parroquia','EL GUAYABO',327),('parroquia','GENERAL URDANETA',328),('parroquia','LIBERTADOR',328),('parroquia','MANUEL GUANIPA MATOS',328),('parroquia','MARCELINO BRICEÑO',328),('parroquia','SAN TIMOTEO',328),('parroquia','PUEBLO NUEVO',328),('parroquia','PEDRO LUCAS URRIBARRI',329),('parroquia','SANTA RITA',329),('parroquia','JOSE CENOVIO URRIBARR',329),('parroquia','EL MENE',329),('parroquia','SANTA CRUZ DEL ZULIA',330),('parroquia','URRIBARRI',330),('parroquia','MORALITO',330),('parroquia','SAN CARLOS DEL ZULIA',330),('parroquia','SANTA BARBARA',330),('parroquia','LUIS DE VICENTE',331),('parroquia','RICAURTE',331),('parroquia','MONS.MARCOS SERGIO G',331),('parroquia','SAN RAFAEL',331),('parroquia','LAS PARCELAS',331),('parroquia','TAMARE',331),('parroquia','LA SIERRITA',331),('parroquia','BOLIVAR',332),('parroquia','COQUIVACOA',332),('parroquia','CRISTO DE ARANZA',332),('parroquia','CHIQUINQUIRA',332),('parroquia','SANTA LUCIA',332),('parroquia','OLEGARIO VILLALOBOS',332),('parroquia','JUANA DE AVILA',332),('parroquia','CARACCIOLO PARRA PEREZ',332),('parroquia','IDELFONZO VASQUEZ',332),('parroquia','CACIQUE MARA',332),('parroquia','CECILIO ACOSTA',332),('parroquia','RAUL LEONI',332),('parroquia','FRANCISCO EUGENIO B',332),('parroquia','MANUEL DAGNINO',332),('parroquia','LUIS HURTADO HIGUERA',332),('parroquia','VENANCIO PULGAR',332),('parroquia','ANTONIO BORJAS ROMERO',332),('parroquia','SAN ISIDRO',332),('parroquia','FARIA',333),('parroquia','SAN ANTONIO',333),('parroquia','ANA MARIA CAMPOS',333),('parroquia','SAN JOSE',333),('parroquia','ALTAGRACIA',333),('parroquia','GOAJIRA',334),('parroquia','ELIAS SANCHEZ RUBIO',334),('parroquia','SINAMAICA',334),('parroquia','ALTA GUAJIRA',334),('parroquia','SAN JOSE DE PERIJA',335),('parroquia','BARTOLOME DE LAS CASAS',335),('parroquia','LIBERTAD',335),('parroquia','RIO NEGRO',335),('parroquia','GIBRALTAR',336),('parroquia','HERAS',336),('parroquia','M.ARTURO CELESTINO A',336),('parroquia','ROMULO GALLEGOS',336),('parroquia','BOBURES',336),('parroquia','EL BATEY',336),('parroquia','ANDRES BELLO (KM 48)',337),('parroquia','POTRERITOS',337),('parroquia','EL CARMELO',337),('parroquia','CHIQUINQUIRA',337),('parroquia','CONCEPCION',337),('parroquia','ELEAZAR LOPEZ C',338),('parroquia','ALONSO DE OJEDA',338),('parroquia','VENEZUELA',338),('parroquia','CAMPO LARA',338),('parroquia','LIBERTAD',338),('parroquia','UDON PEREZ',339),('parroquia','ENCONTRADOS',339),('parroquia','DONALDO GARCIA',340),('parroquia','SIXTO ZAMBRANO',340),('parroquia','EL ROSARIO',340),('parroquia','AMBROSIO',341),('parroquia','GERMAN RIOS LINARES',341),('parroquia','JORGE HERNANDEZ',341),('parroquia','LA ROSA',341),('parroquia','PUNTA GORDA',341),('parroquia','CARMEN HERRERA',341),('parroquia','SAN BENITO',341),('parroquia','ROMULO BETANCOURT',341),('parroquia','ARISTIDES CALVANI',341),('parroquia','RAUL CUENCA',342),('parroquia','LA VICTORIA',342),('parroquia','RAFAEL URDANETA',342),('parroquia','JOSE RAMON YEPEZ',343),('parroquia','LA CONCEPCION',343),('parroquia','SAN JOSE',343),('parroquia','MARIANO PARRA LEON',343),('parroquia','MONAGAS',344),('parroquia','ISLA DE TOAS',344),('parroquia','MARCIAL HERNANDEZ',345),('parroquia','FRANCISCO OCHOA',345),('parroquia','SAN FRANCISCO',345),('parroquia','EL BAJO',345),('parroquia','DOMITILA FLORES',345),('parroquia','LOS CORTIJOS',345),('parroquia','BARI',346),('parroquia','JESUS M SEMPRUN',346),('parroquia','SIMON RODRIGUEZ',347),('parroquia','CARLOS QUEVEDO',347),('parroquia','FRANCISCO J PULGAR',347),('parroquia','RAFAEL MARIA BARALT',348),('parroquia','MANUEL MANRIQUE',348),('parroquia','RAFAEL URDANETA',348),('parroquia','FERNANDO GIRON TOVAR',349),('parroquia','LUIS ALBERTO GOMEZ',349),('parroquia','PARHUEÑA',349),('parroquia','PLATANILLAL',349),('parroquia','CM. SAN FERNANDO DE ATABA',350),('parroquia','UCATA',350),('parroquia','YAPACANA',350),('parroquia','CANAME',350),('parroquia','CM. MAROA',351),('parroquia','VICTORINO',351),('parroquia','COMUNIDAD',351),('parroquia','CM. SAN CARLOS DE RIO NEG',352),('parroquia','SOLANO',352),('parroquia','COCUY',352),('parroquia','CM. ISLA DE RATON',353),('parroquia','SAMARIAPO',353),('parroquia','SIPAPO',353),('parroquia','MUNDUAPO',353),('parroquia','GUAYAPO',353),('parroquia','CM. SAN JUAN DE MANAPIARE',354),('parroquia','ALTO VENTUARI',354),('parroquia','MEDIO VENTUARI',354),('parroquia','BAJO VENTUARI',354),('parroquia','CM. LA ESMERALDA',355),('parroquia','HUACHAMACARE',355),('parroquia','MARAWAKA',355),('parroquia','MAVACA',355),('parroquia','SIERRA PARIMA',355),('parroquia','SAN JOSE',356),('parroquia','VIRGEN DEL VALLE',356),('parroquia','SAN RAFAEL',356),('parroquia','JOSE VIDAL MARCANO',356),('parroquia','LEONARDO RUIZ PINEDA',356),('parroquia','MONS. ARGIMIRO GARCIA',356),('parroquia','MCL.ANTONIO J DE SUCRE',356),('parroquia','JUAN MILLAN',356),('parroquia','PEDERNALES',357),('parroquia','LUIS B PRIETO FIGUERO',357),('parroquia','CURIAPO',358),('parroquia','SANTOS DE ABELGAS',358),('parroquia','MANUEL RENAUD',358),('parroquia','PADRE BARRAL',358),('parroquia','ANICETO LUGO',358),('parroquia','ALMIRANTE LUIS BRION',358),('parroquia','IMATACA',359),('parroquia','ROMULO GALLEGOS',359),('parroquia','JUAN BAUTISTA ARISMEN',359),('parroquia','MANUEL PIAR',359),('parroquia','5 DE JULIO',359),('parroquia','CARABALLEDA',360),('parroquia','CARAYACA',360),('parroquia','CARUAO',360),('parroquia','CATIA LA MAR',360),('parroquia','LA GUAIRA',360),('parroquia','MACUTO',360),('parroquia','MAIQUETIA',360),('parroquia','NAIGUATA',360),('parroquia','EL JUNKO',360),('parroquia','PQ RAUL LEONI',360),('parroquia','PQ CARLOS SOUBLETTE',360);

insert into call_center (cal_nombre, cal_apellido, cal_fecha_nacimiento, cal_telefono, cal_tipo_usuario, cal_correo, cal_password) values ('Terry', 'Lopez', DATE'01-01-1990', '1093832', 'supervisor', 'terry@gmail.com', 'claveterry');
insert into constante (con_identificador, con_valor) values ('margenGanancia', '2.5');
